/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionList: typeof import('./src/components/action/action-list.vue')['default']
    ActionModal: typeof import('./src/components/action/action-modal.vue')['default']
    ActionPanel: typeof import('./src/components/action/action-panel.vue')['default']
    ActionSection: typeof import('./src/components/action/action-section.vue')['default']
    ChangeLanguage: typeof import('./src/components/change-language.vue')['default']
    DefineIcons: typeof import('./src/components/icons/define-icons.vue')['default']
    IconItem: typeof import('./src/components/icon-item.vue')['default']
    NoResults: typeof import('./src/components/no-results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLang: typeof import('./src/components/select-lang.vue')['default']
    SetAutostart: typeof import('./src/components/set-autostart.vue')['default']
    SvgIcon: typeof import('./src/components/icons/svg-icon.vue')['default']
    TranslateDetail: typeof import('./src/components/translate-detail.vue')['default']
    TranslateList: typeof import('./src/components/translate-list.vue')['default']
  }
}
