/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconMoon: typeof import('./src/components/icons/icon-moon.vue')['default']
    MoonIcon: typeof import('./src/components/icons/icon-moon.vue')['default']
    NoResults: typeof import('./src/components/no-results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
