/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionPanel: typeof import('./src/components/action/action-panel.vue')['default']
    ActionSection: typeof import('./src/components/action/action-section.vue')['default']
    DefineIcons: typeof import('./src/components/icons/define-icons.vue')['default']
    IconItem: typeof import('./src/components/icon-item.vue')['default']
    NoResults: typeof import('./src/components/no-results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLang: typeof import('./src/components/select-lang.vue')['default']
    SvgIcon: typeof import('./src/components/icons/svg-icon.vue')['default']
    WordList: typeof import('./src/components/word-list.vue')['default']
    WordResult: typeof import('./src/components/word-result.vue')['default']
  }
}
